### ISSUE TITLE
Project feedback .

### ISSUE THREAD

**Issue by Umangmsharma** [airavata-courses/ampersand#27]
Hi,

Our team DSDummies  was trying to review your project. 
While tryin to clone your project repository I couldn't see any files except the documentation files.  Seems like your code isn't merged yet. Please correct me if we're mistaken.

Also, we saw the installation steps from your wiki, and it looks like a lot of effort to run these many steps. Did your team try to dockerize the  application or any shell scripts to make it easy for the TA to run your application ?

Feedback from team DSDummies : https://github.com/airavata-courses/DSDummies

**Comment by apednek** [comment]
Hi Umang,
We have mentioned in our wiki to switch to release/project-milestone-1 branch. Please read the steps carefully and let me know in case of any further queries.

![image](https://user-images.githubusercontent.com/31995443/153329276-b7fa77c7-4ab2-4acd-adf9-f1180eed3e4e.png)

Thanks,
Team Ampersand

**Comment by kamblenikhil** [comment]
Hey,
Thank you for your feedback.

1. I see you are trying to setup our project. After cloning our repo, you will see the master branch and as our wiki page states you need to switch to "release/project-milestone-1" branch and follow the further instructions.
2. The installation steps might take a lot of effort but our project will run end-to-end successfully.
3. Due to time constraint we could only dockerize two of our microservices.

Thank you,
Team Ampersand
